### ISSUE TITLE
Test with fast-refresh

### ISSUE THREAD

**Issue by gsimone** [pmndrs/use-tweaks#10]
Probably breaks right now

**Comment by neefrehman** [comment]
can confirm FR doesn't work too well. I either get no updates, or sudden extra nested panes!
![image](https://user-images.githubusercontent.com/29544565/97588144-1b8ef380-19f4-11eb-92be-8c321980386b.png)

**Comment by gsimone** [comment]
Maybe trying to avoid double-creation is the wrong approach, maybe we should look into contributing a way to remove panes in Tweakpane so that react can cleanup on update/hmr
