### ISSUE TITLE
Monitors

### ISSUE THREAD

**Issue by gsimone** [pmndrs/use-tweaks#12]
API for monitors, maybe a fn that hides constants or something

```js
const  { mouseMonitor, x, y  } = useTweaks({ mouseMonitor: makeMonitor('2d'), x: 1, y: 1 })

// alt
const  { mouseMonitor, x, y  } = useTweaks({ mouseMonitor: { type: "MONITOR" }, x: 1, y: 1 })

useFrame(() => {
   mouseMonitor.set(mouse.x)

   // alt
  mouseMonitor(mouse.x)
})
 
```

**Comment by CptCompiler** [comment]
hey @gsimone, 
why did you close this issue?
Is there any way to use monitors?
Thanks. Nice work so far!

**Comment by dbismut** [comment]
Reopening! Pretty sure Gianmarco was already thinking of the new magic api he has in mind, but first things first!

**Comment by gsimone** [comment]
Hey @CptCompiler we had them working in the previous API, but weren't too happy about it. Monitors are special in that they have to be imperatively set by the user, original API was something like:

```jsx
const [monitor,setMonitor] = createMonitor(...)

useTweaks(monitor)

// your imperative code
setMonitor(4)
```

Opinions?

**Comment by gsimone** [comment]
@dbismut proposes using a ref, which we feel is more react-like

```jsx
const ref = useRef(0)
useTweaks("Monitor", {
  ...otherTweaks,
  ...makeMonitor(ref, "MyMonitorName", ...settings))
}

// setting the ref value to update the monitor
useFrame(({ clock }) => { ref.current = Math.sin(clock.getElapsedTime()) })
```

**Comment by CptCompiler** [comment]
Thanks for your fast replies, guys!

Hmm... I think I would prefer refs as well. Sounds good.

**Comment by gsimone** [comment]
If you want you can give some feedback in PR #35

**Comment by CptCompiler** [comment]
Yeah... thank you very much. Keep up the good work! 🎉
