### ISSUE TITLE
Fields don't get disposed properly when outside directories

### ISSUE THREAD

**Issue by gsimone** [pmndrs/use-tweaks#23]
To reproduce:

- make a component that can be mounted/unmounted
- add a tweak in the component
- if the tweak is in a directory, it will be disposed when unmounting, otherwise it will be re-created

![image](https://user-images.githubusercontent.com/1862172/97777985-240e3800-1b74-11eb-84a5-102abd05b844.png)

**Comment by dbismut** [comment]
Should be fixed in #26
