### ISSUE TITLE
`useTweaks` type not working

### ISSUE THREAD

**Issue by ivanross** [pmndrs/use-tweaks#38]
## Description

`useTweaks` return type is always `any`.

## Example

```ts

const tweaks = useTweaks({ first: 10 }) // has type any

```

https://codesandbox.io/s/usetweaks-type-issue-1k2lo

**Comment by gsimone** [comment]
@ivanross useTweaks should be used as a generic, the signature is
```ts
export function useTweaks<T extends Schema>(schema: T, settings?: Settings): UseTweaksValues<T>
```

So
```ts
  const tweaks = useTweaks<{ first: number }>({ first: 10 });
```

I do agree that it doesn't seem to be working, though

@dbismut I remember this was working in the examples, could it be a problem with the npm bundle?

**Comment by ivanross** [comment]
Hi @gsimone thank you for the quick answer!

I see that `useTweaks` is generic, and if you check the codesandbox it seems that Typescript understands it

![image](https://user-images.githubusercontent.com/15856208/100358895-1aeb7c00-2ff7-11eb-8269-083ed5649a92.png)

**Comment by dbismut** [comment]
Hi guys, I don't know what's happening... This is what I get in the example from the repo, maybe there's something wrong when bundling types as you're saying GM... We're using TypeScript 4, not sure if this has an impact but even upgrading @ivanross sandbox didn't seem to solve it...

But in any case:

```ts
// you shouldn't be using the shouldn't need to do this
const tweaks = useTweaks<{ first: number }>({ first: 10 });

// this should work instead
const tweaks = useTweaks({ first: 10 });
```

<img width="794" alt="image" src="https://user-images.githubusercontent.com/5003380/100375588-52b1ee00-300e-11eb-8e6a-cc462d0884d1.png">

**Comment by ivanross** [comment]
@gsimone @dbismut Just opened a PR to solve this!
